/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import EDD.Documento;
import EDD.Usuario;
import Funciones.FunctionTXT;
import Funciones.LeerArchivo;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static proyectoedd_2_colaprioridad.Main.tiempoInicioSimulacion;
import static proyectoedd_2_colaprioridad.Main.usuarios;

/**
 *
 * @author francisco
 */
public class AgregarDocumentoCola extends javax.swing.JFrame {

    /**
     * Creates new form AgregarDocumento
     */
    public AgregarDocumentoCola() {
        initComponents();
        InicializarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ListaUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        AgregarDocumento = new javax.swing.JButton();
        txtPrioridad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ListaDocumentos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 106, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaUsuariosMouseClicked(evt);
            }
        });
        jPanel2.add(ListaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 270, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Usuarios:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prioridad: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("!! El nivel de prioridad alterara su orden de impresion !!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        Exit.setBackground(new java.awt.Color(102, 102, 102));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Salir");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 50, 30));

        AgregarDocumento.setBackground(new java.awt.Color(51, 51, 51));
        AgregarDocumento.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AgregarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        AgregarDocumento.setText("Agregar Documento");
        AgregarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 30));

        txtPrioridad.setEditable(false);
        txtPrioridad.setName(""); // NOI18N
        jPanel2.add(txtPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Documentos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 20));

        jPanel2.add(ListaDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 270, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaUsuariosMouseClicked
        // TODO add your handling code here:
        ListaDocumentos.removeAllItems();
        Object selectedItem = ListaUsuarios.getSelectedItem();
        
       Usuario usuarioSeleccionado = getUsuarioSeleccionado(usuarios, selectedItem.toString());
        
        if (usuarioSeleccionado != null){
            
            txtPrioridad.setText( Integer.toString(usuarioSeleccionado.prioridad));
            for (Documento documento : usuarioSeleccionado.documentos) {
                ListaDocumentos.addItem(documento.nombre);
            }
        }
        
    }//GEN-LAST:event_ListaUsuariosMouseClicked

    private void AgregarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocumentoActionPerformed
        // TODO add your handling code here:
        Object selectedUsuarioItem = ListaUsuarios.getSelectedItem();
        Object selectedDocumentoItem = ListaDocumentos.getSelectedItem();
        Usuario usuarioSeleccionado = getUsuarioSeleccionado(usuarios, selectedUsuarioItem.toString());
        Documento documentoSeleccionado = getDocumentoSeleccionado(usuarioSeleccionado, selectedDocumentoItem.toString());
        int tiempo = CalcularTiempo(usuarioSeleccionado.prioridad);
        //arbolDocumentoEncolados = 
        AgregarDocumentoArchivo(documentoSeleccionado.nombre, tiempo, documentoSeleccionado.size);
    }//GEN-LAST:event_AgregarDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDocumentoCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDocumentoCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDocumentoCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDocumentoCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDocumentoCola().setVisible(true);
            }
        });
    }
    
     private void InicializarComboBox() {
        
        LeerArchivo f = new LeerArchivo();
        FunctionTXT content = new FunctionTXT();
        String listaUsuarios = f.leertxt("src\\Files\\usuarios.csv");
        String listDocumentos = f.leertxt("src\\Files\\documentos.csv");
        usuarios = content.getUsuarios(listaUsuarios);
        usuarios = content.addDocumentosUsuario(usuarios, listDocumentos);
        ListaUsuarios.removeAll();
        for (Usuario usuario : usuarios) {
             ListaUsuarios.addItem(usuario.nombre);
        }
     
    }
     
    private Usuario getUsuarioSeleccionado(List<Usuario> usuarios, String nombreUsuario) {
        Usuario usuarioSeleccionado = null;
        for (Usuario usuario : usuarios) {
             if (usuario.nombre.trim().equalsIgnoreCase(nombreUsuario.trim())) {
                 usuarioSeleccionado = usuario;
                 break;
             }
        }
        
        return usuarioSeleccionado;
    }
    
    private Documento getDocumentoSeleccionado(Usuario usuario, String nombreDocumento){
        Documento documentoSeleccionado = null;
        for (Documento documento : usuario.documentos) {
             if (documento.nombre.trim().equalsIgnoreCase(nombreDocumento.trim())) {
                 documentoSeleccionado = documento;
                 break;
             }
        }
        
        return documentoSeleccionado;
    }
    
    private void AgregarDocumentoArchivo(String nombreDocumento, int tiempo, int size) {
        // TODO add your handling code here:
        LeerArchivo f = new LeerArchivo();
        FunctionTXT content = new FunctionTXT();
        String listDocumentosEncolados = f.leertxt("src\\Files\\documentosEncolados.csv");
        String documentoNuevo = nombreDocumento + ", " + Integer.toString(tiempo) + ", " + Integer.toString(size);
        listDocumentosEncolados += documentoNuevo + "\n";      
        
        content.escribir_documentosEncolados(listDocumentosEncolados);
    }
    
    private int CalcularTiempo(int prioridad) {
        int tiempo = 60; // 1 min en segundos
        Calendar calendar = Calendar.getInstance();
        Date currentTime = calendar.getTime();
        
        long diffTime =  currentTime.getTime() - tiempoInicioSimulacion.getTime();
        long result = diffTime/1000;
        int diffSec = Long.valueOf(result).intValue();
        return ((tiempo*prioridad)+diffSec);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDocumento;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> ListaDocumentos;
    private javax.swing.JComboBox<String> ListaUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPrioridad;
    // End of variables declaration//GEN-END:variables
}
