/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import EDD.Cola;
import org.graphstream.graph.Graph;
import Funciones.FuncionCola;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import static proyectoedd_2_colaprioridad.Main.tiempoInicioSimulacion;

/**
 *
 * @author yaxim
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }
    
    FuncionCola funcionesCola = new FuncionCola();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InciarSimulacion = new javax.swing.JButton();
        CargarArchivo = new javax.swing.JButton();
        EliminarUsuario = new javax.swing.JButton();
        CrearDocumento = new javax.swing.JButton();
        AgregarDocumento = new javax.swing.JButton();
        EliminarDocumento = new javax.swing.JButton();
        ColaImpresion = new javax.swing.JButton();
        AgregarUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 112, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenida");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 320, 50));

        InciarSimulacion.setBackground(new java.awt.Color(51, 51, 51));
        InciarSimulacion.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        InciarSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        InciarSimulacion.setText("Iniciar Simulación");
        InciarSimulacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InciarSimulacionActionPerformed(evt);
            }
        });
        jPanel2.add(InciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));

        CargarArchivo.setBackground(new java.awt.Color(51, 51, 51));
        CargarArchivo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel2.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, -1));

        EliminarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        EliminarUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        EliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        EliminarUsuario.setText("Eliminar Usuarios");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        CrearDocumento.setBackground(new java.awt.Color(51, 51, 51));
        CrearDocumento.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CrearDocumento.setForeground(new java.awt.Color(255, 255, 255));
        CrearDocumento.setText("Agregar Documentos");
        CrearDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(CrearDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 200, -1));

        AgregarDocumento.setBackground(new java.awt.Color(51, 51, 51));
        AgregarDocumento.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AgregarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        AgregarDocumento.setText("Agregar Documentos Cola");
        AgregarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, -1));

        EliminarDocumento.setBackground(new java.awt.Color(51, 51, 51));
        EliminarDocumento.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        EliminarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        EliminarDocumento.setText("Eliminar Documentos");
        EliminarDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(EliminarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, -1));

        ColaImpresion.setBackground(new java.awt.Color(51, 51, 51));
        ColaImpresion.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ColaImpresion.setForeground(new java.awt.Color(255, 255, 255));
        ColaImpresion.setText("Visualizar Cola de Impresión");
        ColaImpresion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColaImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaImpresionActionPerformed(evt);
            }
        });
        jPanel2.add(ColaImpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 200, 20));

        AgregarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        AgregarUsuario.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AgregarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        AgregarUsuario.setText("Agregar Usuarios");
        AgregarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lista Usurios y Documentos");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar Documento Encolado");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // TODO add your handling code here:
        
        CargarArchivo cargar = new CargarArchivo ();
        cargar.setVisible(true);
        cargar.setLocationRelativeTo(null);
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        // TODO add your handling code here:
        
        AgregarUsuario adUser = new AgregarUsuario();
        adUser.setVisible(true);
        adUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
        
        EliminarUsuario deleteUser = new EliminarUsuario();
        deleteUser.setVisible(true);
        deleteUser.setLocationRelativeTo(null); 
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void CrearDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocumentoActionPerformed
        // TODO add your handling code here:
        
        CrearDocumento create = new CrearDocumento();
        create.setVisible(true);
        create.setLocationRelativeTo(null); 
    }//GEN-LAST:event_CrearDocumentoActionPerformed

    private void AgregarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocumentoActionPerformed
        // TODO add your handling code here:
        
        AgregarDocumentoCola adDocument = new AgregarDocumentoCola();
        adDocument.setVisible(true);
        adDocument.setLocationRelativeTo(null); 
        
    }//GEN-LAST:event_AgregarDocumentoActionPerformed

    private void EliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocumentoActionPerformed
        // TODO add your handling code here:
        
        EliminarDocumento deleteDocument = new EliminarDocumento();
        deleteDocument.setVisible(true);
        deleteDocument.setLocationRelativeTo(null);
    }//GEN-LAST:event_EliminarDocumentoActionPerformed

    private void ColaImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaImpresionActionPerformed
        // TODO add your handling code here:
        Cola cola = funcionesCola.crearCola();
        Graph dibujoCola = funcionesCola.drawColaImpresion(cola);
        funcionesCola.viewCola(dibujoCola);
    }//GEN-LAST:event_ColaImpresionActionPerformed

    private void InciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InciarSimulacionActionPerformed
        // TODO add your handling code here:
        Calendar calendar = Calendar.getInstance();
        tiempoInicioSimulacion = calendar.getTime();
        //Calendar calendarInicial = calendar.setTime(tiempoInicioSimulacion);
        
        
        JOptionPane.showMessageDialog(null, "Iniciando simulación: " + tiempoInicioSimulacion.toString());
    }//GEN-LAST:event_InciarSimulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDocumento;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton ColaImpresion;
    private javax.swing.JButton CrearDocumento;
    private javax.swing.JButton EliminarDocumento;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JButton InciarSimulacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
